# Program 1

In [ ]:
my_list = ['A','B','C','D']
x = len(my_list)
for i in range(x):
    print("positive index : ",i,"negative index: ",i-x)

# Program 2

In [ ]:
def f1():
    print("This is function")

class Student:
    def info(self):
        print("This is method")

s=Student()
s.info()

In [ ]:
f1()


In [ ]:
print('HI')

In [3]:
import numpy as np

In [4]:
data = np.random.randn(2,3)

In [5]:
data

array([[ 0.13491706, -1.64669596, -0.12650785],
       [-0.37348902,  0.86697009,  0.27873487]])

In [6]:
data *10

array([[  1.34917061, -16.4669596 ,  -1.26507846],
       [ -3.7348902 ,   8.66970092,   2.78734875]])

In [7]:
data+ data

array([[ 0.26983412, -3.29339192, -0.25301569],
       [-0.74697804,  1.73394018,  0.55746975]])